### ISSUE TITLE
Example doesn't work with latest go-webauthn version

### ISSUE THREAD

**Issue by gnur** [NHAS/webauthn-example#1]
Hi,

I wanted to use your example to build upon as it is a clean setup without too much frameworks getting in the way.

However, when cloning this repo and doing a `go mod -u ./...` it doesn't work anymore. It seems like somewhere between 

```
-require github.com/go-webauthn/webauthn v0.5.0
+require github.com/go-webauthn/webauthn v0.8.2
```

Something changed with the format of the key supplied, resulting in this error:

```
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at bufferDecode (http://localhost:8080/:33:30)
    at Object.<anonymous> (http://localhost:8080/:62:59)
    at e (https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js:2:29453)
    at t (https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js:2:29755)
```

The corresponding line:

```javascript
credentialCreationOptions.publicKey.challenge = bufferDecode(credentialCreationOptions.publicKey.challenge);
```

Do you have any idea how this could be fixed?

**Comment by mbetel** [comment]
I replaced the function bufferDecode with:

```
function bufferDecode(base64String) {
      const padding = '='.repeat((4 - base64String.length % 4) % 4);
      const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');

      const rawData = window.atob(base64);
      const outputArray = new Uint8Array(rawData.length);

      for (let i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i);
      }

      return outputArray;
    }
```

**Comment by NHAS** [comment]
Hi. Sorry I totally forgot to respond to this.

You can see the way I've used the library  in https://github.com/NHAS/wag
